project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!upcoming-posts-notes/"

website:
  title: "Dr. C. C. Gill"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CCGill
      - icon: linkedin
        href: https://www.linkedin.com/in/christopher-c-gill
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

