---
title: Genetics Resources
author: "CG"
date: "2024-11-23"
date-modified: "2024-11-23"
categories: [resources, genetics, data-science]
---

I'm fortunate to have worked in areas I find fascinating, so when people ask me about a topic I work on I nearly always enjoy discussing it, and if they're interested enough I like to pass on some useful resources I've found.  However, I rely on bookmarks and google far too much to find resources, so this post is intended to enable me and hopefully others to find these references.

I was fortunate to work in the labs of [Jonathan Marchini](https://jmarchini.org/) and [Simon Myers](https://myersgroup.github.io/) on some aspects of population genetics and functional genomics.  This post will focus on genetics resources, and initially mostly population genetics.  As I have very limited time today I will add just a few free learning resources from population genetics and later will add some of the others I have planned.

## Population Genetics Resources

When I have time I will add in a recommended reading list of books I have enjoyed and that give a good grounding in population genetics, both empirical and theoretical.

- [Graham Coop's Population and Quantitative Genetics book](https://github.com/cooplab/popgen-notes/releases) - population genetics notes from [the Coop lab](), this is an immensely useful resource.  I really appreciated the coverage of many aspects of the subject that are "well known", and therefore no longer referenced, but often difficult to pin down for newcomers to the field[^footnote1].  
- [The Coop lab blog](https://gcbias.org)

[^footnote1]: I think everyone who has worked in research and had to find their way around a new field will be familiar with this - that when a concept or technique is well-known enough it is no longer referenced in the literature (except PhD Theses or occasionally survey papers).  The challenge is to discern when a concept is well-known enough that it no longer requires explanation or referencing in new publications.  This is even more of a challenge in interdisciplinary work in which collaborating scientists have differing views of what is "well-known".  

- [Jonathan Pritchard's An Owner' Guide to the Human Genome: an introduction to human population genetics, variation and disease](https://web.stanford.edu/group/pritchardlab/HGbook.html) - an excellent resource from Jonathan Pritchard. The [Pritchard lab page](https://web.stanford.edu/group/pritchardlab/home.html) is well worth a visit.
