---
title: Resources for learning R
author: "CG"
date: "2024-10-31"
date-modified: "2024-12-15"
categories: [resources, R, data-science, software-development]
---

This is a collection of resources I have found over the years that I find myself returning to or recommending to others.

R is described as  "a free software environment for statistical computing and graphics" at the [R project for Statistical Computing](https://www.r-project.org/).  For me the strength of R is not only as a programming language but also a powerful statistical computing system, it is relatively easy to use for statistical analysis and has excellent facilities to easily produce publication quality plots.

Coming from a background in pure mathematics, my first exposure to coding and software development was in MatLab, MAGMA and GAP.  I later branched out into C, C++ and Python.  My exposure to MAGMA and GAP was mainly in algebraic and combinatoric algorithms, but it was in R that I first really got to grips with statistical computing.  Over the years I have written several R packages for data visualisation tools, tools to analyse electronic health data, and developed highly optimized R packages providing statistical machine learning algorithms for the analysis of large scale single cell RNA-seq datasets.  I have optimized my R code extensively, integrated C++ code, made use of Rmarkdown (and now quarto) for data analysis and building websites, and it is still my primary tool for data visualisation.  I have also taught students to use R over several years, so hopefully the resources I point to here will be useful.

## Free Resources

### Data Science and software development

Hadley Wickham and the posit team have produced some excellent resources, which tend to promote their tidyverse tooling.

- [R for Data Science](https://r4ds.hadley.nz/): The introductory book from Hadley Wickham, an excellent resource for beginners and intermediate users alike.
- [R packages](https://r-pkgs.org/): Hadley WIckham and Jennifer Bryan's excellent introduction to building R packages.
- [Advanced R](https://adv-r.hadley.nz/): An advanced book from Hadley Wickham - I thoroughly enjoyed it, the content is excellent and well written, but is for established R users.
- [What they forgot to teach you about R](https://rstats.wtf/) Although still a work in progress, this site has some very useful context on how R works and also generally good advice on tried-and-tested good habits to adopt.


Roger Peng has produced a handy book covering some aspects of software development in R.  This is excellent if you're serious about developing packages, but may not be for you if you are mostly interested in analysis.

- [Mastering Software Development with R](https://bookdown.org/rdpeng/RProgDA/): a very useful book from Roger Peng and others.

## Introductory books/courses

The excellent R for Data Science book referenced above is one of many good introductory books and courses available, all of which have a different perspective.

The following books start more or less "from scratch", so are excellent if you're just getting started.

- [Data Analysis for the Life Sciences](https://github.com/genomicsclass/labs?tab=readme-ov-file): a useful introductory book from Rafael Irizarry
- [Introduction to Data Science: Data Analysis and Prediction Algorithms with R](https://rafalab.dfci.harvard.edu/dsbook/): another book from Rafael Irizarry
- [Exploratory Data Analysis with R](https://bookdown.org/rdpeng/exdata/) Roger Peng's introductory book on exploratory data analysis.  Some of the chapters are a little brief, but it has several good starting points.

Robin Evans' University of Oxford [Statistical Computing course](https://www.stats.ox.ac.uk/~evans/statprog/index2.htm)

### Integrating C++ with R through Rcpp

In some cases, optimizing your R code can only go so far, and some lower-level programming is required.  I've found the Rcpp suite of packages very helpful in automating the build and bindings to expose C++ code in my R packages.  Particularly Rcpp, RcppArmadillo and RcppEigen.

- [Rcpp](https://www.rcpp.org/)
- [Rcpp gallery](https://gallery.rcpp.org/)

### Visualisation

R is capable of producing beautiful publication-ready figures.  While I don't subscribe to the notion that one tool is inherently better than any others, I find the ggplot2 library and in particular the grammar of graphics expressive and efficient.  This is particularly helpful during exploratory analyses, helping to iterate quickly.

- [Introduction to ggplot2](https://ggplot2.tidyverse.org/articles/ggplot2.html): an introduction to ggplot2 from the tidyverse team
- [An introduction to ggplot2](https://www.datanovia.com/en/lessons/introduction-to-ggplot2/): a useful introduction with examples.
- [Fundamentals of Data Visualisation](https://clauswilke.com/dataviz/) an excellent introduction from cowplot developer Claus O. Wilke
- [ggplot2 book](https://ggplot2-book.org/introduction.html) : not the best place to start for beginners, but worth reading once familiar with the basics (if you are a beginner, stick to R for Data Science for the basics).
- [R graph gallery](https://r-graph-gallery.com/) this is an excellent resource, particulary when getting started.

### Code Style

- [The tidyverse style guide](https://style.tidyverse.org/) Personally, I have found this an excellent resource, and comparison with the Google style guide was time well-spent.

### Other useful resources

- [The Arrow R cookbook](https://arrow.apache.org/cookbook/r/) an excellent cookbook of approaches to use arrow tooling in R.
- [R Manuals](https://cran.r-project.org/manuals.html) Again, this is rather a lot of detail if you are starting out, but for an advanced user it can be a useful resource.
- [Writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) This is an excellent resource once you're established with building R packages.  To get started I recommend the book by Hadley Wickham and Jennifer Bryan linked above.

### Selected blogs and resources

- [The R blog](https://blog.r-project.org/) for discussions about upcoming features in R.  Probably for advanced users.

Several of these links I return to time and time again, so I am sure I will return to this page to dig them out in the near future.